export const DEATH_CAUSES = new Map([
  ["fall", "fall"], ["void", "void"], ["fire", "fire"], ["lava", "lava"],
  ["drowning", "drowning"], ["explosion", "explosion"], ["projectile", "arrow"],
  ["magic", "magic"], ["wither", "wither"], ["starve", "starve"], ["contact", "cactus"],
  ["anvil", "anvil"], ["magma", "magma"], ["lightning", "lightning"], ["freezing", "freeze"],
  ["cramming", "cramming"], ["flyIntoWall", "kinetic"], ["dryout", "dryout"],
  ["temperature", "temperature"], ["sonicBoom", "sonic_boom"],
]);

export const TOOL_REGISTRY = new Map([
  ["wooden_pickaxe", { material: "wooden", type: "pickaxe" }],
  ["stone_pickaxe", { material: "stone", type: "pickaxe" }],
  ["iron_pickaxe", { material: "iron", type: "pickaxe" }],
  ["golden_pickaxe", { material: "golden", type: "pickaxe" }],
  ["diamond_pickaxe", { material: "diamond", type: "pickaxe" }],
  ["netherite_pickaxe", { material: "netherite", type: "pickaxe" }],
  ["wooden_sword", { material: "wooden", type: "sword" }],
  ["stone_sword", { material: "stone", type: "sword" }],
  ["iron_sword", { material: "iron", type: "sword" }],
  ["golden_sword", { material: "golden", type: "sword" }],
  ["diamond_sword", { material: "diamond", type: "sword" }],
  ["netherite_sword", { material: "netherite", type: "sword" }],
  ["wooden_axe", { material: "wooden", type: "axe" }],
  ["stone_axe", { material: "stone", type: "axe" }],
  ["iron_axe", { material: "iron", type: "axe" }],
  ["golden_axe", { material: "golden", type: "axe" }],
  ["diamond_axe", { material: "diamond", type: "axe" }],
  ["netherite_axe", { material: "netherite", type: "axe" }],
  ["wooden_shovel", { material: "wooden", type: "shovel" }],
  ["stone_shovel", { material: "stone", type: "shovel" }],
  ["iron_shovel", { material: "iron", type: "shovel" }],
  ["golden_shovel", { material: "golden", type: "shovel" }],
  ["diamond_shovel", { material: "diamond", type: "shovel" }],
  ["netherite_shovel", { material: "netherite", type: "shovel" }],
  ["wooden_hoe", { material: "wooden", type: "hoe" }],
  ["stone_hoe", { material: "stone", type: "hoe" }],
  ["iron_hoe", { material: "iron", type: "hoe" }],
  ["golden_hoe", { material: "golden", type: "hoe" }],
  ["diamond_hoe", { material: "diamond", type: "hoe" }],
  ["netherite_hoe", { material: "netherite", type: "hoe" }],
  ["trident", { material: "special", type: "trident" }],
  ["crossbow", { material: "special", type: "crossbow" }],
  ["bow", { material: "special", type: "bow" }],
  ["mace", { material: "special", type: "mace" }],
]);

export const DEATH_MESSAGES = {
  void: ["§c%player% was lost in the void!", "§c%player% discovered that the void has no bottom...", "§c%player% decided to explore the infinite", "§c%player% was absorbed by darkness", "§c%player% fell out of world"],
  fall: ["§c%player% forgot that gravity exists", "§c%player% thought he could fly", "§cSplat! %player% crashed to the ground", "§c%player% should have brought a parachute", "§c%player% miscalculated that jump", "§c%player% discovered the law of gravity", "§c%player% did not measure the distance correctly"],
  fire: ["§c%player% became barbecue", "§c%player% played with fire... and lost", "§c%player% was consumed by flames", "§c%player% melted like ice cream", "§c%player% did not resist the heat"],
  lava: ["§c%player% thought the lava was a pool", "§c%player% took a very hot bath", "§c%player% swam in the wrong place", "§c%player% became part of the Nether", "§c%player% tested the temperature of the lava"],
  drowning: ["§c%player% forgot he needed to breathe", "§c%player% found Atlantis... permanently", "§c%player% should have brought gills", "§c%player% ran out of bubbles", "§c%player% decided to live under the sea"],
  explosion: ["§c%player% exploded into a thousand pieces", "§cBOOM! %player% is no longer with us", "§c%player% got too close to a Creeper", "§c%player% discovered that TNT is dangerous"],
  arrow: ["§c%player% was pierced by an arrow", "§c%player% didn\'t see that arrow coming", "§c%player% was converted to a pincushion", "§c%player% received a special delivery"],
  magic: ["§c%player% succumbed to magic", "§c%player% was the victim of a deadly spell", "§c%player% did not resist the arcane power"],
  wither: ["§c%player% withered to death", "§c%player% was consumed by the darkness of the Wither", "§c%player% did not survive the Wither effect"],
  starve: ["§c%player% forgot to eat", "§c%player% died of hunger", "§c%player% should have made more provisions"],
  cactus: ["§c%player% hugged a cactus", "§c%player% discovered that cacti are pointy", "§c%player% was pricked to death"],
  anvil: ["§c%player% was crushed by an anvil", "§cBONK! %player% looked up too late", "§c%player% had a close encounter with gravity and an anvil"],
  magma: ["§c%player% discovered that magma burns", "§c%player% danced on magma", "§c%player% thought the magma was safe"],
  lightning: ["§c%player% was struck by lightning", "§cZAP! %player% was electrocuted", "§c%player% attracted the wrath of Zeus"],
  freeze: ["§c%player% froze to death", "§c%player% turned into an ice cube", "§c%player% should have dressed better"],
  cramming: ["§c%player% was crushed by too many entities", "§c%player% had no room to breathe"],
  kinetic: ["§c%player% crashed into a wall at high speed", "§c%player% miscalculated his landing with elytra"],
  dryout: ["§c%player% dried out of the water", "§c%player% needed water to survive"],
  temperature: ["§c%player% could not withstand the extreme temperature", "§c%player% died due to temperature change"],
  sonic_boom: ["§c%player% was disintegrated by a sonic wave", "§c%player% did not survive the Warden\'s scream"],
  pvp: {
    suicide: ["§c%player% deleted himself", "§c%player% decided to end his own existence", "§c%player% discovered a creative way to commit suicide", "§c%player% couldn\'t handle himself", "§c%player% removed himself from the game"],
    weapon: {
      sword: ["§c%killer% pierced %player% with his %weapon%", "§c%killer% made %player% sushi with his %weapon%", "§c%player% tested the edge of %killer%\'s %weapon%", "§c%killer% demonstrated his skill with the %weapon% on %player%"],
      axe: ["§c%killer% felled %player% with his %weapon%", "§c%player% was split in two by %killer%\'s %weapon%", "§c%killer% turned %player% into firewood with his %weapon%", "§c%killer% gave %player% a lethal ax blow"],
      pickaxe: ["§c%killer% undermined %player% with his %weapon%", "§c%player% got drilled by %killer%\'s %weapon%", "§c%killer% found a new use for his %weapon% in %player%", "§c%killer% dug up %player%\'s grave with his %weapon%"],
      shovel: ["§c%killer% buried %player% with his %weapon%", "§c%player% was hit with %killer%\'s %weapon%", "§c%killer% dug %player%\'s grave with his %weapon%"],
      hoe: ["§c%killer% cultivated %player% with his %weapon%", "§c%player% was created by %killer%\'s %weapon%", "§c%killer% found an unexpected use for his %weapon% in %player%"],
      trident: ["§c%killer% skewered %player% with his %weapon%", "§c%player% was impaled by %killer%\'s %weapon%", "§c%killer% demonstrated his aim with the %weapon%"],
      bow: ["§c%killer% hit a perfect shot on %player%", "§c%player% was hunted by %killer% with his %weapon%", "§c%killer% has lethal aim with his %weapon%"],
      crossbow: ["§c%killer% shot %player% accurately", "§c%player% did not dodge %killer%\'s crossbow", "§c%killer% uploaded and downloaded his %weapon% to %player%"],
      mace: ["§c%killer% crushed %player% with his %weapon%", "§c%player% felt the full weight of %killer%\'s %weapon%", "§c%killer% demonstrated the power of his %weapon%"],
    },
    default: ["§c%killer% sent %player% to the lobby", "§c%killer% gave %player% a free trip to the lobby", "§c%player% was destroyed by %killer%", "§c%killer% taught %player% who\'s boss", "§c%player% tested the power of %killer%", "§c%killer% removed %player% from the server", "§c%player% was humiliated by %killer%", "§c%killer% taught %player% a lesson", "§c%player% will wish he never crossed paths with %killer%", "§c%killer% sent %player% to sleep"],
  },
  mob: {
    zombie: ["§c%player% was eaten by a zombie", "§c%player% joined the undead army", "§c%player% couldn\'t escape the zombies"],
    zombie_villager: ["§c%player% was infected by a zombie villager", "§c%player% fell to a converted villager"],
    husk: ["§c%player% was mummified by a Husk", "§c%player% dried up in the desert"],
    drowned: ["§c%player% was dragged into the depths", "§c%player% was a victim of the deep sea", "§c%player% couldn\'t swim fast enough"],
    skeleton: ["§c%player% was mowed down by a skeleton", "§c%player% received too many arrows", "§c%player% was the perfect target"],
    stray: ["§c%player% was frozen by a Stray", "§c%player% felt the cold of the frozen arrows"],
    wither_skeleton: ["§c%player% was withered by a Nether skeleton", "§c%player% did not survive the Nether"],
    creeper: ["§c%player% didn\'t hear the \'ssssss\'", "§c%player% hugged a Creeper", "§cBOOM! %player% flew through the air"],
    spider: ["§c%player% was a spider\'s lunch", "§c%player% got caught in the wrong web", "§c%player% didn\'t see those eight legs coming"],
    cave_spider: ["§c%player% was poisoned by a cave spider", "§c%player% explored too deep"],
    blaze: ["§c%player% was incinerated by a Blaze", "§c%player% turned into ashes", "§c%player% couldn\'t resist the fireballs"],
    ghast: ["§c%player% was hit by a fireball", "§c%player% didn\'t dodge the Ghast in time", "§c%player% heard the last lament"],
    magma_cube: ["§c%player% was absorbed by a Magma Cube", "§c%player% melted when touching living lava"],
    piglin: ["§c%player% angered the piglins", "§c%player% forgot to put on golden armor"],
    piglin_brute: ["§c%player% was crushed by a Brute Piglin", "§c%player% underestimated brute force"],
    hoglin: ["§c%player% was hit by a Hoglin", "§c%player% turned into bacon"],
    zoglin: ["§c%player% was torn apart by a zombified Zoglin", "§c%player% could not tame the beast"],
    enderman: ["§c%player% looked in the wrong eyes", "§c%player% bothered an Enderman", "§c%player% was teleported to his death"],
    endermite: ["§c%player% was eaten by a tiny Endermite", "§c%player% underestimated the little parasite"],
    shulker: ["§c%player% floated to his death", "§c%player% was raised by a Shulker", "§c%player% was unable to land safely"],
    ender_dragon: ["§c%player% was roasted by the Dragon of the End", "§c%player% wasn\'t ready for the final boss"],
    wither: ["§c%player% was disintegrated by the Wither", "§c%player% succumbed to the power of the Wither", "§c%player% did not survive the apocalypse"],
    witch: ["§c%player% was bewitched to death", "§c%player% drank the wrong potion", "§c%player% was a victim of dark magic"],
    phantom: ["§c%player% should have slept more", "§c%player% was hunted from the skies", "§c%player% ignored the bed for too long"],
    slime: ["§c%player% was absorbed by a Slime", "§c%player% drowned in jelly"],
    silverfish: ["§c%player% was devoured by Silverfish", "§c%player% broke the wrong block"],
    guardian: ["§c%player% was pierced by the laser beam", "§c%player% did not respect the guardian of the ocean"],
    elder_guardian: ["§c%player% was cursed by the Elder Guardian", "§c%player% felt eternal mining fatigue"],
    pufferfish: ["§c%player% died from a puffer fish XD", "§c%player% was poisoned by an inflated fish"],
    bee: ["§c%player% was stung to death", "§c%player% upset the wrong hive"],
    wolf: ["§c%player% was eaten by wolves", "§c%player% shouldn\'t have bothered the pack"],
    polar_bear: ["§c%player% was torn apart by a polar bear", "§c%player% got too close to the babies"],
    panda: ["§c%player% was crushed by an angry panda", "§c%player% bothered the wrong panda"],
    goat: ["§c%player% was attacked by a goat", "§c%player% flew through the air down the mountain"],
    iron_golem: ["§c%player% was thrown into the air", "§c%player% angered the village protector"],
    warden: ["§c%player% woke up the Warden... and didn\'t live to tell the tale", "§c%player% was silenced by the guardian of the depths", "§c%player% shouldn\'t have made so much noise"],
    breeze: ["§c%player% was blown away by the wind", "§c%player% flew too high because of a Breeze"],
    bogged: ["§c%player% was poisoned by a Bogged", "§c%player% got lost in the swamp"],
    creaking: ["§c%player% was stalked by a Creaking", "§c%player% shouldn\'t have walked alone in the pale forest", "§c%player% was hunted by the forest creature", "§c%player% could not escape Creaking", "§c%player% became prey to the forest guardian"],
    tnt: ["§c%player% played with TNT... and lost", "§cBOOM! %player% was blown to pieces", "§c%player% lit the wrong fuse", "§c%player% turned into fireworks", "§c%player% miscalculated the distance of the explosion", "§c%player% discovered that TNT is not decorative", "§c%player% went ka-boom and disappeared", "§c%player% got too close to the dynamite", "§c%player% tested the explosive power firsthand", "§c%player% turned on more than he could handle"],
  },
  other: ["§c%player% has met an unfortunate end", "§c%player% has left us in a mysterious way", "§cRest in peace, %player%", "§c%player% found a creative way to die"],
};

export const UNKNOWN_ENTITY_MESSAGES = [
  "§c%player% was eliminated by a mysterious creature", "§c%player% found something that shouldn\'t exist",
  "§c%player% was a victim of the unknown", "§c%player% encountered a strange entity",
  "§c%player% was defeated by something inexplicable", "§c%player% discovered a new way to die",
  "§c%player% was attacked by an unidentified creature",
];

export const UNKNOWN_DEATH_CAUSE_MESSAGES = [
  "§c%player% died of mysterious causes", "§c%player% found a new way to leave",
  "§c%player% had a very peculiar ending", "§c%player% was a victim of strange circumstances",
  "§c%player% discovered a new type of danger", "§c%player% died in a very creative way",
  "§c%player% surprised us with his unique death",
];
